# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fca0c29ef55cdd227beb8b09e015ec6af0dd9ce66b7f46a32e07be9a7fb219f66b8bd8276e8fa99e17a87c6e2c3b3911a6f37c25b445f14cfb5aabfa9c50c03

test:
  secret_key_base: eca74f1f847d48aa4b752be9941e5992640836cd05dfafa47e587535807408e9443e9ccb9457c2974bb0692a0980af8bf9ca6fe7c96e59a00759b17b6e3004d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
